load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "localization_lmd_predictor",
    hdrs = [
        "predictor.h",
    ],
    deps = [
        "//modules/common/status",
        "//modules/localization/proto:localization_proto",
    ],
)

cpplint()
